parameters:
#    one_stop_shop_item.example.class: OneStopShop\ItemBundle\Example

services:
#    one_stop_shop_item.example:
#        class: %one_stop_shop_item.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    one_stop_shop_item.type.item:
        class: OneStopShop\ItemBundle\Form\Type\ItemType
        tags:
            - { name: form.type, alias: item }
            
    one_stop_shop_item.type.itemPrice:
        class: OneStopShop\ItemBundle\Form\Type\ItemPriceType
        tags:
            - { name: form.type, alias: itemPrice }
    