parameters:
#    one_stop_shop_home.example.class: OneStopShop\HomeBundle\Example

services:
#    one_stop_shop_home.example:
#        class: %one_stop_shop_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
