OneStopShop\DatabaseBundle\Entity\Items:
    type: entity
    table: items
    fields:
        itemNo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: item_no
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 30
            fixed: false
            nullable: false
        description:
            type: string
            length: 300
            fixed: false
            nullable: true
    manyToMany:
        orderNo:
            targetEntity: Orders
            cascade: {  }
            mappedBy: itemNo
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
