OneStopShop\DatabaseBundle\Entity\ItemOrders:
    type: entity
    table: item_orders
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        quantity:
            type: integer
            unsigned: false
            nullable: false
    manyToOne:
        orderNo:
            targetEntity: Orders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_no:
                    referencedColumnName: order_no
            orphanRemoval: false
        itemNo:
            targetEntity: Items
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                item_no:
                    referencedColumnName: item_no
            orphanRemoval: false
    lifecycleCallbacks: {  }
