OneStopShop\DatabaseBundle\Entity\LOCustomers:
    type: entity
    table: l_o_customers
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        creditLimit:
            type: integer
            unsigned: false
            nullable: true
            column: credit_limit
        creditBalance:
            type: integer
            unsigned: false
            nullable: true
            column: credit_balance
        brn:
            type: string
            length: 11
            fixed: false
            nullable: false
    manyToOne:
        cid:
            targetEntity: Customers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: CID
            orphanRemoval: false
    lifecycleCallbacks: {  }
