OneStopShop\DatabaseBundle\Entity\MailOrders:
    type: entity
    table: mail_orders
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        orderNo:
            targetEntity: Orders
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_no:
                    referencedColumnName: order_no
            orphanRemoval: false
        cid:
            targetEntity: MoCustomers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: cid
            orphanRemoval: false
    lifecycleCallbacks: {  }
