OneStopShop\DatabaseBundle\Entity\MoCustomers:
    type: entity
    table: mo_customers
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        email:
            type: string
            length: 25
            fixed: false
            nullable: false
        trn:
            type: string
            length: 20
            fixed: false
            nullable: false
    manyToOne:
        cid:
            targetEntity: Customers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cid:
                    referencedColumnName: CID
            orphanRemoval: false
    lifecycleCallbacks: {  }
