OneStopShop\DatabaseBundle\Entity\Orders:
    type: entity
    table: orders
    fields:
        orderNo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: order_no
            generator:
                strategy: IDENTITY
        date:
            type: date
            nullable: false
    lifecycleCallbacks: {  }
