parameters:
#    one_stop_shop_order.example.class: OneStopShop\OrderBundle\Example

services:
#    one_stop_shop_order.example:
#        class: %one_stop_shop_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
