one_stop_shop_customer_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: OneStopShopCustomerBundle:Default:index }

add_customer:
    pattern: /addCustomer
    defaults: { _controller: OneStopShopCustomerBundle:Customer:addCustomer }