parameters:
#    one_stop_shop_customer.example.class: OneStopShop\CustomerBundle\Example

services:
#    one_stop_shop_customer.example:
#        class: %one_stop_shop_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    one_stop_shop_customer.type.customer:
        class: OneStopShop\CustomerBundle\Form\Type\CustomerType
        tags:
            - { name: form.type, alias: customer }